theme: jekyll-theme-hacker
title: Blog de clase para la materia de Tecnologías para el desarrollo de aplicaciones web.
author: Santiago Gutiérrez, Santiago Henao, Angie Dahiana Vargas, Luisa María Zapata.
