-- MySQL Script generated by MySQL Workbench
-- Sat Apr 10 16:14:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(255) NOT NULL,
  `passUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `permisos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipoPermiso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marcas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idMarcas` INT NOT NULL,
  `Modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modelos_marcas1_idx` (`idMarcas` ASC) ,
  CONSTRAINT `fk_modelos_marcas1`
    FOREIGN KEY (`idMarcas`)
    REFERENCES `marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proveedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipoFuncionamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipoFuncionamiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipoRiesgo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipoRiesgo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ubicacionDispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ubicacionDispositivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Piso` VARCHAR(45) NOT NULL,
  `Habitacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `modelos` INT NOT NULL,
  `Estado` TINYINT NULL,
  `fechaMantenimiento` DATE NULL,
  `proveedor` INT NOT NULL,
  `tipoFuncionamiento` INT NOT NULL,
  `tipoRiesgo` INT NOT NULL,
  `ubicacionDispositivo` INT NOT NULL,
  `registroInvima` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inventario_modelos1_idx` (`modelos` ASC) ,
  INDEX `fk_inventario_proveedores1_idx` (`proveedor` ASC) ,
  INDEX `fk_inventario_tipoFuncionamiento1_idx` (`tipoFuncionamiento` ASC) ,
  INDEX `fk_inventario_tipoRiesgo1_idx` (`tipoRiesgo` ASC) ,
  INDEX `fk_inventario_ubicacionDispositivo1_idx` (`ubicacionDispositivo` ASC) ,
  CONSTRAINT `fk_inventario_modelos1`
    FOREIGN KEY (`modelos`)
    REFERENCES `modelos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_proveedores1`
    FOREIGN KEY (`proveedor`)
    REFERENCES `proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_tipoFuncionamiento1`
    FOREIGN KEY (`tipoFuncionamiento`)
    REFERENCES `tipoFuncionamiento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_tipoRiesgo1`
    FOREIGN KEY (`tipoRiesgo`)
    REFERENCES `tipoRiesgo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_ubicacionDispositivo1`
    FOREIGN KEY (`ubicacionDispositivo`)
    REFERENCES `ubicacionDispositivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `permisos_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `permisos_usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `permisos_id` INT NOT NULL,
  INDEX `fk_usuarios_has_permisos_permisos1_idx` (`permisos_id` ASC) ,
  INDEX `fk_usuarios_has_permisos_usuarios1_idx` (`usuarios_id` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuarios_has_permisos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_permisos_permisos1`
    FOREIGN KEY (`permisos_id`)
    REFERENCES `permisos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marcas_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marcas_proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marcas_id` INT NOT NULL,
  `proveedores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_marcas_has_proveedores_proveedores1_idx` (`proveedores_id` ASC) ,
  INDEX `fk_marcas_has_proveedores_marcas1_idx` (`marcas_id` ASC) ,
  CONSTRAINT `fk_marcas_has_proveedores_marcas1`
    FOREIGN KEY (`marcas_id`)
    REFERENCES `marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marcas_has_proveedores_proveedores1`
    FOREIGN KEY (`proveedores_id`)
    REFERENCES `proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
